site_name: Fatih Yürünebilir Rotalar
site_description: İstanbul/Fatih için yürüme mesafesine göre gruplanmış gezi planı
theme:
  name: material
  language: tr
nav:
  - Anasayfa: index.md
markdown_extensions:
  - tables
  - admonition
  - toc:
      permalink: true
