site_name: İstanbul Yürünebilir Rotalar
site_description: Fatih, Kuzguncuk, Beyoğlu, Üsküdar, Kadıköy için klasterli yürüyüş planları
theme:
  name: material
  language: tr
nav:
  - Anasayfa: index.md
markdown_extensions:
  - tables
  - admonition
  - toc:
      permalink: true
