$schema: "https://json-schema.org/draft/2020-12/schema"
title: Itinerary
properties:
  id: { type: string, description: "benzersiz id (slug)" }
  title: { type: string, description: "Görünen başlık" }
  region: { type: string, description: "Bölge/şehir" }
  language: { type: string, enum: [tr, en], default: tr }
  days:
    type: array
    description: "Gün planları"
    items:
      type: object
      properties:
        date: { type: string, description: "YYYY-MM-DD (opsiyonel)" }
        label: { type: string, description: "Gün etiketi (1. Gün vb.)" }
        notes: { type: string }
        stops:
          type: array
          items:
            type: object
            properties:
              time: { type: string, description: "HH:MM" }
              name: { type: string }
              type: { type: string, description: "müze, yürüyüş, yeme-içme, tekne vb." }
              address: { type: string }
              duration_min: { type: integer }
              cost_try: { type: number }
              booking:
                type: object
                properties:
                  url: { type: string }
                  ref: { type: string }
              notes: { type: string }
  logistics:
    type: object
    properties:
      season: { type: string }
      best_time: { type: string }
      transport: { type: string }
      tips: { type: array, items: { type: string } }
  totals:
    type: object
    properties:
      estimated_cost_try: { type: number }
      total_duration_min: { type: integer }
required: [id, title, region, days]
